<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: wikator
 * Date: Tue, 22 Nov 2022 14:38:26 +0300
 */

$conf['title'] = 'folderwiki';
$conf['start'] = 'st';
$conf['license'] = '';
$conf['basedir'] = '/folderwiki/';
$conf['breadcrumbs'] = 0;
$conf['dformat'] = '%Y-%m-%d %H:%M';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,check';
$conf['htmlok'] = 1;
$conf['sitemap'] = 5;
$conf['updatecheck'] = 0;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['proxy']['ssl'] = 1;
$conf['plugin']['discussion']['automatic'] = 1;
$conf['plugin']['discussion']['moderate'] = 1;
$conf['plugin']['htmlsafe']['filter'] = 'html,head,meta,link,title,body,script,object,applet,embed,video,form,button,input';
$conf['plugin']['semantic']['useMetaAuthor'] = 0;
$conf['plugin']['semantic']['useOpenGraph'] = 1;
$conf['plugin']['semantic']['exposeWebService'] = 0;
$conf['plugin']['semantic']['hideMail'] = 1;
$conf['tpl']['dokubook']['sb_pagename'] = 'sidebar';
$conf['plugin']['indexmenu']['only_admins'] = '1';
$conf['tpl']['vector']['vector_userpage'] = '0';
$conf['tpl']['vector']['vector_discuss'] = '0';
$conf['tpl']['vector']['vector_sitenotice'] = '0';
$conf['tpl']['vector']['vector_sitenotice_translate'] = '0';
$conf['tpl']['vector']['vector_navigation_location'] = ':sidebar';
$conf['tpl']['vector']['vector_copyright_default'] = '0';
$conf['plugin']['authpdo']['debug'] = '1';
$conf['plugin']['addnewpage']['addpage_hideACL'] = '1';
