<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: wikator
 * Date: Tue, 29 Jun 2021 13:29:33 +0300
 */

$conf['title'] = 'folderwiki';
$conf['start'] = 'st';
$conf['license'] = '';
$conf['breadcrumbs'] = 0;
$conf['dformat'] = '%Y-%m-%d %H:%M';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,check';
$conf['htmlok'] = 1;
$conf['sitemap'] = 5;
$conf['updatecheck'] = 0;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['proxy']['ssl'] = 1;
$conf['plugin']['indexmenu']['only_admins'] = 1;
$conf['plugin']['authpdo']['debug'] = '1';
$conf['plugin']['addnewpage']['addpage_hideACL'] = '1';
